workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    integrations:
      app_store_connect: CodeMagic Api Key 1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.MyAppWatcher"
      vars:
        APP_BUNDLE_ID: "com.MyAppWatcher"
        SHARE_EXTENSION_BUNDLE_ID: "com.MyAppWatcher.MyAppWatcherShareID"
        
        APP_PROVISIONING_PROFILE: "AppWatcherProvisioning"
        SHARE_EXTENSION_PROVISIONING_PROFILE: "AppWatcherExtensionProvisioning"
        
        # Codemagic автоматически создает переменную $CM_TEAM_ID
        # TEAM_ID: "H2V698KL5P" # Можно указать явно, но $CM_TEAM_ID надежнее
        
        XCODE_PROJECT: "AppWatcher.xcodeproj"
        XCODE_SCHEME: "AppWatcher"
        APP_STORE_APPLE_ID: 6754845203
      xcode: 16.0
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          # Этот скрипт все еще нужен для этапа архивации
          PROJECT_FILE="$CM_BUILD_DIR/$XCODE_PROJECT/project.pbxproj"
          echo "Setting up manual code signing for archive..."
          sed -i.bak -E 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/' "$PROJECT_FILE"
          sed -i.bak -E "/PRODUCT_BUNDLE_IDENTIFIER = ${APP_BUNDLE_ID//./\\.}/,/;/ s/PROVISIONING_PROFILE_SPECIFIER = \".*\";/PROVISIONING_PROFILE_SPECIFIER = \"$APP_PROVISIONING_PROFILE\";/" "$PROJECT_FILE"
          sed -i.bak -E "/PRODUCT_BUNDLE_IDENTIFIER = ${SHARE_EXTENSION_BUNDLE_ID//./\\.}/,/;/ s/PROVISIONING_PROFILE_SPECIFIER = \".*\";/PROVISIONING_PROFILE_SPECIFIER = \"$SHARE_EXTENSION_PROVISIONING_PROFILE_UUID\";/" "$PROJECT_FILE"
          echo "Code signing settings for archive applied."

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          echo "Latest uploaded build number from App Store Connect: $LATEST_BUILD_NUMBER"
          if [ -z "$LATEST_BUILD_NUMBER" ] || [ "$LATEST_BUILD_NUMBER" == "null" ] || ! [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]] || [ "$LATEST_BUILD_NUMBER" -lt 1 ]; then
            NEW_BUILD_NUMBER=1
          else
            NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          fi
          echo "Setting new build number to: $NEW_BUILD_NUMBER"
          agvtool new-version -all $NEW_BUILD_NUMBER

      - name: Build ipa for distribution
        script: |
          # --- НОВЫЙ БЛОК: Создаем export_options.plist ---
          echo "Creating export_options.plist..."
          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$APP_BUNDLE_ID</key>
                  <string>$APP_PROVISIONING_PROFILE</string>
                  <key>$SHARE_EXTENSION_BUNDLE_ID</key>
                  <string>$SHARE_EXTENSION_PROVISIONING_PROFILE</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>teamID</key>
              <string>$CM_TEAM_ID</string>
          </dict>
          </plist>
          EOF

          echo "export_options.plist created:"
          cat export_options.plist
          # --- КОНЕЦ НОВОГО БЛОКА ---

          # --- ИЗМЕНЕНИЕ: Добавляем путь к нашему файлу ---
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "export_options.plist"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - eldig98986976758746356789654o02@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
