workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    integrations:
      app_store_connect: CodeMagic Api Key 1
    environment:
      ios_signing:
        distribution_type: app_store
        # Убираем bundle_identifier отсюда, так как управляем им в скрипте
      vars:
        # Переменные для бандлов
        APP_BUNDLE_ID: "com.MyAppWatcher"
        SHARE_EXTENSION_BUNDLE_ID: "com.MyAppWatcher.MyAppWatcherShareID" # Обновлено
        
        # Переменные для профилей
        APP_PROVISIONING_PROFILE: "AppWatcherProvisioning" # Из скриншота
        SHARE_EXTENSION_PROVISIONING_PROFILE: "AppWatcherExtensionProvisioning" # Из скриншота
        
        # Общие переменные
        XCODE_PROJECT: "AppWatcher.xcodeproj"
        XCODE_SCHEME: "AppWatcher"
        APP_STORE_APPLE_ID: 6754845203
      xcode: 16.0
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          # Явно указываем профили для каждого таргета
          # Сначала для основного приложения
          xcode-project use-profiles \
            --project "$XCODE_PROJECT" \
            --bundle-id "$APP_BUNDLE_ID" \
            --profile-name "$APP_PROVISIONING_PROFILE"
            
          # Затем для расширения
          xcode-project use-profiles \
            --project "$XCODE_PROJECT" \
            --bundle-id "$SHARE_EXTENSION_BUNDLE_ID" \
            --profile-name "$SHARE_EXTENSION_PROVISIONING_PROFILE"

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          echo "Latest uploaded build number from App Store Connect: $LATEST_BUILD_NUMBER"
          if [ -z "$LATEST_BUILD_NUMBER" ] || [ "$LATEST_BUILD_NUMBER" == "null" ] || ! [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]] || [ "$LATEST_BUILD_NUMBER" -lt 1 ]; then
            NEW_BUILD_NUMBER=1
          else
            NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          fi
          echo "Setting new build number to: $NEW_BUILD_NUMBER"
          agvtool new-version -all $NEW_BUILD_NUMBER

      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      # ... (ваша секция publishing без изменений)
